// <auto-generated />
namespace infinite.mvc.dogstore.test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dogstoreandBreed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dogstoreandBreed));
        
        string IMigrationMetadata.Id
        {
            get { return "202301221647086_dogstoreandBreed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
