// <auto-generated />
namespace infinite.mvc.dogstore.test.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DogstoreandBreedName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DogstoreandBreedName));
        
        string IMigrationMetadata.Id
        {
            get { return "202301211805543_DogstoreandBreedName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
